apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "convoy-scheduler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "convoy-scheduler.name" . }}
    helm.sh/chart: {{ include "convoy-scheduler.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "convoy-scheduler.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        updatedAt: {{ now | quote }}
      labels:
        app.kubernetes.io/name: {{ include "convoy-scheduler.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: convoy-config
              mountPath: /config
          command: ["/cmd"]
          args: ["scheduler", "--config", "/config/convoy.json"]
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          env:
            - name: SERVICE_NAME
              value: "{{ .Chart.Name }}"
            - name: PORT
              value: {{ .Values.app.port | quote }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
