apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "convoy-migrate.fullname" . }}
  annotations:
    {{- if .Values.jobAnnotations }}
    {{- toYaml .Values.jobAnnotations | nindent 4 }}
    {{- end }}
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ include "convoy-migrate.name" . }}
    helm.sh/chart: {{ include "convoy-migrate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          {{- if .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}          
          command: ["/cmd"]
          args: ["migrate", "up"]
          env:
           {{- if .Values.global.externalDatabase.enabled }}
            - name: CONVOY_DB_SCHEME
              value: {{ .Values.global.externalDatabase.scheme | quote }}
            - name: CONVOY_DB_HOST
              value: {{ .Values.global.externalDatabase.host | quote }}
            - name: CONVOY_DB_PORT
              value: {{ .Values.global.externalDatabase.port | quote }}
            - name: CONVOY_DB_USERNAME
              value: {{ .Values.global.externalDatabase.username | quote }}
            {{- if ne .Values.global.externalDatabase.secret "" }}
            - name: CONVOY_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.externalDatabase.secret }}"
                  key: password
            {{- else }}
            - name: CONVOY_DB_PASSWORD
              value: {{ .Values.global.externalDatabase.password | quote }}
            {{- end }}
            - name: CONVOY_DB_DATABASE
              value: {{ .Values.global.externalDatabase.database | quote }}
            - name: CONVOY_DB_OPTIONS
              value: {{ .Values.global.externalDatabase.options | quote }}
            {{- end }}
            {{- if .Values.global.nativeRedis.enabled }}
            - name: CONVOY_REDIS_HOST
              value: {{ .Values.global.nativeRedis.host | quote }}
            {{- if ne .Values.global.nativeRedis.secret "" }}
            - name: CONVOY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.nativeRedis.secret }}"
                  key: password
            {{- else }}
            - name: CONVOY_REDIS_PASSWORD
              value: {{ .Values.global.nativeRedis.password | quote }}
            {{- end }}
            - name: CONVOY_REDIS_PORT
              value: {{ .Values.global.nativeRedis.port | quote }}
            - name: CONVOY_REDIS_TYPE
              value: "NATIVE"
            {{- end }}
            {{- if .Values.global.externalRedis.enabled }}
            {{- if .Values.global.externalRedis.addresses }}
            - name: CONVOY_REDIS_CLUSTER_ADDRESSES
              value: {{ .Values.global.externalRedis.addresses | quote }}
            {{- else }}
            - name: CONVOY_REDIS_TYPE
              value: "EXTERNAL"
            - name: CONVOY_REDIS_HOST
              value: {{ .Values.global.externalRedis.host | quote }}
            {{- if ne .Values.global.externalRedis.secret "" }}
            - name: CONVOY_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.externalRedis.secret }}"
                  key: password
            {{- else }}
            - name: CONVOY_REDIS_PASSWORD
              value: {{ .Values.global.externalRedis.password | quote }}
            {{- end }}
            - name : CONVOY_REDIS_PORT
              value: {{ .Values.global.externalRedis.port | quote }}
            - name: CONVOY_REDIS_SCHEME
              value: {{ .Values.global.externalRedis.scheme | quote }}
            - name : CONVOY_REDIS_USERNAME
              value: {{ .Values.global.externalRedis.username | quote }}
            - name: CONVOY_REDIS_DATABASE
              value: {{ .Values.global.externalRedis.database | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 16 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
