apiVersion: v2
name: agent
description: Convoy Agent Chart
type: application
version: "3.7.4"
appVersion: "v25.12.6"
maintainers:
  - name: Convoy Engineering Team
    email: engineering@getconvoy.io
